In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot

from pandas import read_csv, set_option
from pandas.plotting import scatter_matrix

In [3]:
fraud_data = read_csv('creditcard.csv.zip')

In [4]:
set_option('display.width', 100)
fraud_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [5]:
fraud_data.shape

(284807, 31)

In [6]:
fraud_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [7]:
fraud_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
y= fraud_data["Class"]
X = fraud_data.loc[:, fraud_data.columns != 'Class']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=1/3,random_state=42, stratify=y)

In [9]:
X_train,X_test,y_train,y_test

(            Time        V1        V2        V3        V4        V5        V6        V7        V8  \
 69047    53244.0  1.239616 -0.899952  0.440585 -0.587725 -1.113024 -0.237229 -0.723593  0.069584
 19498    30329.0 -0.813151  1.359829  1.346820  2.550308  0.949065  0.466341  0.661830  0.103189
 215705  140185.0 -1.778866 -2.630909 -0.162263 -0.905025 -0.693729  0.808696  2.386610 -1.007339
 277603  167744.0  2.102894 -0.798484 -1.747327 -0.660742  0.127615  0.160587 -0.385800 -0.074530
 152305   97247.0 -0.961936  0.667170  0.150307 -0.693988  0.542616 -0.287350  0.392661  0.404596
 ...          ...       ...       ...       ...       ...       ...       ...       ...       ...
 3441      2937.0 -0.415022  0.713439  1.221551 -2.108216  0.187067 -1.281616  1.118548 -0.345326
 233802  147710.0  1.993864 -0.516866 -0.620118  0.129845 -0.285128  0.395044 -0.822358  0.231591
 85418    60764.0 -1.497933  0.657921  1.581568 -0.024286  0.584698  1.303031  0.609212  0.135561
 29062    35301.0  1.069777  0.072105  0.496540  1.505318 -0.380277 -0.370243  0.100551 -0.026687
 17677    28847.0 -0.598120  0.775041  1.823394  0.312991 -0.096171 -0.391452  0.499351  0.071224

               V9  ...       V20       V21       V22       V23       V24       V25       V26  \
 69047  -0.497491  ...  0.148049 -0.028444 -0.224935 -0.068355  0.008511  0.403109 -0.334358
 19498  -1.932522  ...  0.004651  0.117034  0.218977 -0.409678 -0.297827  0.307527  0.363862
 215705 -0.285506  ...  0.130881 -0.351949 -0.094951 -0.064063 -0.880709 -0.151423 -0.277071
 277603 -0.532821  ... -0.484321 -0.028297  0.446965 -0.092346 -0.192627  0.299669 -0.017791
 152305  1.195010  ...  0.059251  0.133887  0.632171 -0.109675  0.769799 -0.056814  0.029876
 ...          ...  ...       ...       ...       ...       ...       ...       ...       ...
 3441    0.463473  ...  0.075377  0.132886  0.756938 -0.290888  0.558730  0.037363 -0.871689
 233802  0.995898  ... -0.174051  0.262526  0.884510  0.099141  0.275689 -0.195404  0.623598
 85418   0.452745  ... -0.225079 -0.072452  0.299172  0.110048 -0.615980 -0.425883  0.263968
 29062   0.319684  ... -0.149402 -0.061991 -0.044629 -0.050485  0.400171  0.593314 -0.335160
 17677  -0.017496  ...  0.102259  0.060615  0.568083 -0.084001  0.685003 -0.245859  0.356638

              V27       V28  Amount
 69047  -0.000849  0.013483   74.00
 19498  -0.201548  0.069149    3.71
 215705  0.260784 -0.565981  721.72
 277603 -0.000940 -0.058181   50.00
 152305  0.224941  0.112810   49.20
 ...          ...       ...     ...
 3441    0.239482 -0.020422    1.00
 233802 -0.032455 -0.058552    5.99
 85418  -0.448445  0.045178   36.99
 29062   0.031014  0.024886   45.42
 17677   0.378580  0.206366    6.99

 [189871 rows x 30 columns],
             Time        V1        V2        V3        V4        V5        V6        V7        V8  \
 215048  139915.0  2.176456 -1.528522 -1.433919 -1.681750 -1.053366 -0.757959 -0.861033 -0.209905
 282461  170913.0 -0.845884 -0.330806 -0.044769 -2.072992  1.480658 -1.341421  0.452037 -0.158185
 121268   76130.0 -0.762819  1.312397  1.084885  0.366698  0.810306 -1.530318  1.047306 -0.215369
 193504  130163.0 -3.533256 -0.853753  1.580658 -0.411751 -0.708256  0.542318 -0.861796  0.886444
 158034  110822.0  1.972499 -0.220437 -0.167225  0.552944 -0.671355 -0.723213 -0.576733 -0.128663
 ...          ...       ...       ...       ...       ...       ...       ...       ...       ...
 62882    50465.0 -1.638703  0.889211  1.264046  0.073769  0.090113 -1.239684  0.506667  0.296909
 112473   72661.0  1.228357  0.278820  0.183803  0.504163 -0.161282 -0.559862 -0.020214 -0.034628
 280283  169429.0  1.951544  0.424459 -2.209354  1.593508  0.760917 -1.173650  0.686847 -0.340525
 232467  147182.0  1.913133 -0.717324 -0.344000  0.275969 -0.551489  0.604346 -1.049899  0.376629
 32933    37023.0 -1.818781  1.888458 -1.384778 -0.961102  0.845272  4.631727 -3.180490 -3.392735

               V9  ...       V20       V21       V22       V23       V24       V25       V26  \
 215048 -1.667228  ... -0.342089  0.151601  0.717609 -0.025625 -0.395559  0.025895  0.078794
 282461 -1.730347  ...  0.364525  0.146769  0.087905 -0.103202 -0.572970  0.150608 -0.382606
 121268 -0.806946  ... -0.017272  0.065609  0.150538 -0.277871  0.588722  0.311484 -0.503562
 193504  1.698254  ... -0.509870  0.023474  0.689263  0.144167  0.674687  0.710543  0.180904
 158034  2.698636  ... -0.314091 -0.263990 -0.417787  0.370467 -0.149542 -0.429515 -0.958658
 ...          ...  ...       ...       ...       ...       ...       ...       ...       ...
 62882  -0.768885  ...  0.002727 -0.446565 -1.456008  0.307718  0.324519  0.143817 -0.078503
 112473 -0.199431  ... -0.052909 -0.255381 -0.783247  0.073074 -0.037755  0.226973  0.096992
 280283  0.160307  ... -0.209784 -0.003285  0.114640  0.035559  0.953297  0.407834 -0.546459
 232467  1.293164  ... -0.156024  0.030635  0.035132  0.249086  0.061484 -0.522478  0.154862
 32933  -0.968537  ...  1.045840 -2.462679  0.504691  0.590664  0.960877 -0.580285  0.080453

              V27       V28  Amount
 215048 -0.028473 -0.064036   80.00
 282461  0.055751  0.159270   40.00
 121268  0.100503  0.152010    1.00
 193504 -0.836850  0.221657   12.63
 158034  0.029991 -0.033396   11.27
 ...          ...       ...     ...
 62882   0.016639  0.027874   20.40
 112473 -0.028364  0.017966    5.99
 280283 -0.008554 -0.014634   34.79
 232467 -0.016097 -0.040644   40.53
 32933  -0.374649 -0.030249   50.77

 [94936 rows x 30 columns],
 69047     0
 19498     0
 215705    0
 277603    0
 152305    0
          ..
 3441      0
 233802    0
 85418     0
 29062     0
 17677     0
 Name: Class, Length: 189871, dtype: int64,
 215048    0
 282461    0
 121268    0
 193504    0
 158034    0
          ..
 62882     0
 112473    0
 280283    0
 232467    0
 32933     0
 Name: Class, Length: 94936, dtype: int64)

In [4]:
fraud_data.head(5)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [5]:
fraud_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0